version: "3.2"
services:
  memcached:
    image: memcached:1.6
    command: ["-m", "128m"]

  db:
    image: postgres:12
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  db-volume: