# Generated by Django 3.1.1 on 2020-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
